/*
 * Workflow Execution Service
 *
 * *Run standard workflows on workflow execution platforms in a platform-agnostic way.* ## Executive Summary The Workflow Execution Service (WES) API provides a standard way for users to submit workflow requests to workflow execution systems, and to monitor their execution. This API lets users run a single workflow (currently [**CWL**](https://www.commonwl.org/) or [**WDL**](http://www.openwdl.org/) formatted workflows, other types may be supported in the future) on multiple different platforms, clouds, and environments. Key features of the API: + can request that a workflow be run + can pass parameters to that workflow (e.g. input files, cmdline arguments) + can get information about running workflows (e.g. status, errors, output file locations) + can cancel a running workflow 
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

/// WorkflowEngineVersion : Available workflow engine versions supported by a given instance of the service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct WorkflowEngineVersion {
    /// An array of one or more acceptable engines versions for the `workflow_engine`
    #[serde(rename = "workflow_engine_version", skip_serializing_if = "Option::is_none")]
    pub workflow_engine_version: Option<Vec<String>>,
}

impl WorkflowEngineVersion {
    /// Available workflow engine versions supported by a given instance of the service.
    pub fn new() -> WorkflowEngineVersion {
        WorkflowEngineVersion {
            workflow_engine_version: None,
        }
    }
}

